//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JEdit.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Edit {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Edit() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("JEdit.Resources.Edit", typeof(Edit).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string OverwriteExistingKeystrokeMacro {
            get {
                return ResourceManager.GetString("OverwriteExistingKeystrokeMacro", resourceCulture);
            }
        }
        
        internal static string KeystrokeMacroFile {
            get {
                return ResourceManager.GetString("KeystrokeMacroFile", resourceCulture);
            }
        }
        
        internal static string KeystrokeMacroNotFound {
            get {
                return ResourceManager.GetString("KeystrokeMacroNotFound", resourceCulture);
            }
        }
        
        internal static string LoadKeystrokeMacroSuccessful {
            get {
                return ResourceManager.GetString("LoadKeystrokeMacroSuccessful", resourceCulture);
            }
        }
        
        internal static string SaveKeystrokesAs {
            get {
                return ResourceManager.GetString("SaveKeystrokesAs", resourceCulture);
            }
        }
        
        internal static string EnterNewOutputFileName {
            get {
                return ResourceManager.GetString("EnterNewOutputFileName", resourceCulture);
            }
        }
        
        internal static string InvalidOutputFilename {
            get {
                return ResourceManager.GetString("InvalidOutputFilename", resourceCulture);
            }
        }
        
        internal static string ThisBufferHasNotBeenSaved {
            get {
                return ResourceManager.GetString("ThisBufferHasNotBeenSaved", resourceCulture);
            }
        }
        
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        internal static string UnknownCommand {
            get {
                return ResourceManager.GetString("UnknownCommand", resourceCulture);
            }
        }
        
        internal static string CommandCancelled {
            get {
                return ResourceManager.GetString("CommandCancelled", resourceCulture);
            }
        }
        
        internal static string GoToLine {
            get {
                return ResourceManager.GetString("GoToLine", resourceCulture);
            }
        }
        
        internal static string RepeatCount {
            get {
                return ResourceManager.GetString("RepeatCount", resourceCulture);
            }
        }
        
        internal static string NewFileWarning {
            get {
                return ResourceManager.GetString("NewFileWarning", resourceCulture);
            }
        }
        
        internal static string NoOtherBuffers {
            get {
                return ResourceManager.GetString("NoOtherBuffers", resourceCulture);
            }
        }
        
        internal static string CommandPrompt {
            get {
                return ResourceManager.GetString("CommandPrompt", resourceCulture);
            }
        }
        
        internal static string ModifiedBuffers {
            get {
                return ResourceManager.GetString("ModifiedBuffers", resourceCulture);
            }
        }
        
        internal static string NothingToPlayback {
            get {
                return ResourceManager.GetString("NothingToPlayback", resourceCulture);
            }
        }
        
        internal static string DefiningKeystrokeMacro {
            get {
                return ResourceManager.GetString("DefiningKeystrokeMacro", resourceCulture);
            }
        }
        
        internal static string KeystrokeMacroDefined {
            get {
                return ResourceManager.GetString("KeystrokeMacroDefined", resourceCulture);
            }
        }
        
        internal static string CannotPlayback {
            get {
                return ResourceManager.GetString("CannotPlayback", resourceCulture);
            }
        }
        
        internal static string BackgroundColourNumber {
            get {
                return ResourceManager.GetString("BackgroundColourNumber", resourceCulture);
            }
        }
        
        internal static string ForegroundColourNumber {
            get {
                return ResourceManager.GetString("ForegroundColourNumber", resourceCulture);
            }
        }
        
        internal static string SelectedTitleColourNumber {
            get {
                return ResourceManager.GetString("SelectedTitleColourNumber", resourceCulture);
            }
        }
        
        internal static string NormalTextColourNumber {
            get {
                return ResourceManager.GetString("NormalTextColourNumber", resourceCulture);
            }
        }
        
        internal static string ErrorTextColourNumber {
            get {
                return ResourceManager.GetString("ErrorTextColourNumber", resourceCulture);
            }
        }
        
        internal static string InvalidColour {
            get {
                return ResourceManager.GetString("InvalidColour", resourceCulture);
            }
        }
        
        internal static string InvalidColourIndex {
            get {
                return ResourceManager.GetString("InvalidColourIndex", resourceCulture);
            }
        }
        
        internal static string MaximumKeystrokes {
            get {
                return ResourceManager.GetString("MaximumKeystrokes", resourceCulture);
            }
        }
        
        internal static string UnableToSaveConfig {
            get {
                return ResourceManager.GetString("UnableToSaveConfig", resourceCulture);
            }
        }
        
        internal static string UnableToReadConfig {
            get {
                return ResourceManager.GetString("UnableToReadConfig", resourceCulture);
            }
        }
        
        internal static string CopiedToScrap {
            get {
                return ResourceManager.GetString("CopiedToScrap", resourceCulture);
            }
        }
        
        internal static string SearchFor {
            get {
                return ResourceManager.GetString("SearchFor", resourceCulture);
            }
        }
        
        internal static string PatternNotFound {
            get {
                return ResourceManager.GetString("PatternNotFound", resourceCulture);
            }
        }
        
        internal static string SearchCompleted {
            get {
                return ResourceManager.GetString("SearchCompleted", resourceCulture);
            }
        }
        
        internal static string CaseSensitivityOn {
            get {
                return ResourceManager.GetString("CaseSensitivityOn", resourceCulture);
            }
        }
        
        internal static string CaseSensitivityOff {
            get {
                return ResourceManager.GetString("CaseSensitivityOff", resourceCulture);
            }
        }
        
        internal static string EnterKey {
            get {
                return ResourceManager.GetString("EnterKey", resourceCulture);
            }
        }
        
        internal static string EnterMacroName {
            get {
                return ResourceManager.GetString("EnterMacroName", resourceCulture);
            }
        }
        
        internal static string RegExpOff {
            get {
                return ResourceManager.GetString("RegExpOff", resourceCulture);
            }
        }
        
        internal static string RegExpOn {
            get {
                return ResourceManager.GetString("RegExpOn", resourceCulture);
            }
        }
        
        internal static string RegExpOffStatus {
            get {
                return ResourceManager.GetString("RegExpOffStatus", resourceCulture);
            }
        }
        
        internal static string BlockDeleted {
            get {
                return ResourceManager.GetString("BlockDeleted", resourceCulture);
            }
        }
        
        internal static string DeletedToScrap {
            get {
                return ResourceManager.GetString("DeletedToScrap", resourceCulture);
            }
        }
        
        internal static string Lowercasing {
            get {
                return ResourceManager.GetString("Lowercasing", resourceCulture);
            }
        }
        
        internal static string Uppercasing {
            get {
                return ResourceManager.GetString("Uppercasing", resourceCulture);
            }
        }
        
        internal static string WriteSuccess {
            get {
                return ResourceManager.GetString("WriteSuccess", resourceCulture);
            }
        }
        
        internal static string WriteBlockAs {
            get {
                return ResourceManager.GetString("WriteBlockAs", resourceCulture);
            }
        }
        
        internal static string NewFile {
            get {
                return ResourceManager.GetString("NewFile", resourceCulture);
            }
        }
        
        internal static string Replacement {
            get {
                return ResourceManager.GetString("Replacement", resourceCulture);
            }
        }
        
        internal static string Pattern {
            get {
                return ResourceManager.GetString("Pattern", resourceCulture);
            }
        }
        
        internal static string TranslateComplete {
            get {
                return ResourceManager.GetString("TranslateComplete", resourceCulture);
            }
        }
        
        internal static string TranslatePrompt {
            get {
                return ResourceManager.GetString("TranslatePrompt", resourceCulture);
            }
        }
        
        internal static string NoBackupFiles {
            get {
                return ResourceManager.GetString("NoBackupFiles", resourceCulture);
            }
        }
        
        internal static string BackupFiles {
            get {
                return ResourceManager.GetString("BackupFiles", resourceCulture);
            }
        }
        
        internal static string EnterTabStops {
            get {
                return ResourceManager.GetString("EnterTabStops", resourceCulture);
            }
        }
        
        internal static string InvalidNumber {
            get {
                return ResourceManager.GetString("InvalidNumber", resourceCulture);
            }
        }
        
        internal static string ModifiedBuffer {
            get {
                return ResourceManager.GetString("ModifiedBuffer", resourceCulture);
            }
        }
        
        internal static string PressAnyKey {
            get {
                return ResourceManager.GetString("PressAnyKey", resourceCulture);
            }
        }
        
        internal static string FileToEdit {
            get {
                return ResourceManager.GetString("FileToEdit", resourceCulture);
            }
        }
    }
}
