//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCalc.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Calc {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Calc() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("calc.Resources.Calc", typeof(Calc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string QuitPrompt {
            get {
                return ResourceManager.GetString("QuitPrompt", resourceCulture);
            }
        }
        
        internal static string GotoRowPrompt {
            get {
                return ResourceManager.GetString("GotoRowPrompt", resourceCulture);
            }
        }
        
        internal static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        internal static string EnterColumnWidth {
            get {
                return ResourceManager.GetString("EnterColumnWidth", resourceCulture);
            }
        }
        
        internal static string Worksheet {
            get {
                return ResourceManager.GetString("Worksheet", resourceCulture);
            }
        }
        
        internal static string Range {
            get {
                return ResourceManager.GetString("Range", resourceCulture);
            }
        }
        
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        internal static string Move {
            get {
                return ResourceManager.GetString("Move", resourceCulture);
            }
        }
        
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        internal static string WorksheetInsert {
            get {
                return ResourceManager.GetString("WorksheetInsert", resourceCulture);
            }
        }
        
        internal static string WorksheetDelete {
            get {
                return ResourceManager.GetString("WorksheetDelete", resourceCulture);
            }
        }
        
        internal static string WorksheetColumnWidth {
            get {
                return ResourceManager.GetString("WorksheetColumnWidth", resourceCulture);
            }
        }
        
        internal static string RangeFormat {
            get {
                return ResourceManager.GetString("RangeFormat", resourceCulture);
            }
        }
        
        internal static string RangeAlign {
            get {
                return ResourceManager.GetString("RangeAlign", resourceCulture);
            }
        }
        
        internal static string FileRetrieve {
            get {
                return ResourceManager.GetString("FileRetrieve", resourceCulture);
            }
        }
        
        internal static string FileSave {
            get {
                return ResourceManager.GetString("FileSave", resourceCulture);
            }
        }
        
        internal static string ColumnWidthSet {
            get {
                return ResourceManager.GetString("ColumnWidthSet", resourceCulture);
            }
        }
        
        internal static string ColumnWidthReset {
            get {
                return ResourceManager.GetString("ColumnWidthReset", resourceCulture);
            }
        }
        
        internal static string FormatFixed {
            get {
                return ResourceManager.GetString("FormatFixed", resourceCulture);
            }
        }
        
        internal static string FormatScientific {
            get {
                return ResourceManager.GetString("FormatScientific", resourceCulture);
            }
        }
        
        internal static string FormatCurrency {
            get {
                return ResourceManager.GetString("FormatCurrency", resourceCulture);
            }
        }
        
        internal static string FormatCommas {
            get {
                return ResourceManager.GetString("FormatCommas", resourceCulture);
            }
        }
        
        internal static string FormatGeneral {
            get {
                return ResourceManager.GetString("FormatGeneral", resourceCulture);
            }
        }
        
        internal static string FormatBar {
            get {
                return ResourceManager.GetString("FormatBar", resourceCulture);
            }
        }
        
        internal static string FormatPercent {
            get {
                return ResourceManager.GetString("FormatPercent", resourceCulture);
            }
        }
        
        internal static string FormatDate {
            get {
                return ResourceManager.GetString("FormatDate", resourceCulture);
            }
        }
        
        internal static string FormatText {
            get {
                return ResourceManager.GetString("FormatText", resourceCulture);
            }
        }
        
        internal static string FormatReset {
            get {
                return ResourceManager.GetString("FormatReset", resourceCulture);
            }
        }
        
        internal static string DatesDMY {
            get {
                return ResourceManager.GetString("DatesDMY", resourceCulture);
            }
        }
        
        internal static string DatesDM {
            get {
                return ResourceManager.GetString("DatesDM", resourceCulture);
            }
        }
        
        internal static string DatesMY {
            get {
                return ResourceManager.GetString("DatesMY", resourceCulture);
            }
        }
        
        internal static string AlignLeft {
            get {
                return ResourceManager.GetString("AlignLeft", resourceCulture);
            }
        }
        
        internal static string AlignRight {
            get {
                return ResourceManager.GetString("AlignRight", resourceCulture);
            }
        }
        
        internal static string AlignCentre {
            get {
                return ResourceManager.GetString("AlignCentre", resourceCulture);
            }
        }
        
        internal static string EnterSaveFilename {
            get {
                return ResourceManager.GetString("EnterSaveFilename", resourceCulture);
            }
        }
        
        internal static string EnterEditFilename {
            get {
                return ResourceManager.GetString("EnterEditFilename", resourceCulture);
            }
        }
        
        internal static string CannotOpenFile {
            get {
                return ResourceManager.GetString("CannotOpenFile", resourceCulture);
            }
        }
        
        internal static string CannotSaveFile {
            get {
                return ResourceManager.GetString("CannotSaveFile", resourceCulture);
            }
        }
        
        internal static string Column {
            get {
                return ResourceManager.GetString("Column", resourceCulture);
            }
        }
        
        internal static string Row {
            get {
                return ResourceManager.GetString("Row", resourceCulture);
            }
        }
        
        internal static string RangeAlignDescription {
            get {
                return ResourceManager.GetString("RangeAlignDescription", resourceCulture);
            }
        }
        
        internal static string RangeFormatDescription {
            get {
                return ResourceManager.GetString("RangeFormatDescription", resourceCulture);
            }
        }
        
        internal static string InsertColumnDescription {
            get {
                return ResourceManager.GetString("InsertColumnDescription", resourceCulture);
            }
        }
        
        internal static string InsertRowDescription {
            get {
                return ResourceManager.GetString("InsertRowDescription", resourceCulture);
            }
        }
        
        internal static string SheetInsertDescription {
            get {
                return ResourceManager.GetString("SheetInsertDescription", resourceCulture);
            }
        }
        
        internal static string SheetDeleteDescription {
            get {
                return ResourceManager.GetString("SheetDeleteDescription", resourceCulture);
            }
        }
        
        internal static string SheetColumnWidthDescription {
            get {
                return ResourceManager.GetString("SheetColumnWidthDescription", resourceCulture);
            }
        }
        
        internal static string FormatFixedDescription {
            get {
                return ResourceManager.GetString("FormatFixedDescription", resourceCulture);
            }
        }
        
        internal static string FormatScientificDescription {
            get {
                return ResourceManager.GetString("FormatScientificDescription", resourceCulture);
            }
        }
        
        internal static string FormatCurrencyDescription {
            get {
                return ResourceManager.GetString("FormatCurrencyDescription", resourceCulture);
            }
        }
        
        internal static string FormatCommasDescription {
            get {
                return ResourceManager.GetString("FormatCommasDescription", resourceCulture);
            }
        }
        
        internal static string FormatGeneralDescription {
            get {
                return ResourceManager.GetString("FormatGeneralDescription", resourceCulture);
            }
        }
        
        internal static string FormatBarDescription {
            get {
                return ResourceManager.GetString("FormatBarDescription", resourceCulture);
            }
        }
        
        internal static string FormatPercentDescription {
            get {
                return ResourceManager.GetString("FormatPercentDescription", resourceCulture);
            }
        }
        
        internal static string FormatDatesDescription {
            get {
                return ResourceManager.GetString("FormatDatesDescription", resourceCulture);
            }
        }
        
        internal static string FormatResetDescription {
            get {
                return ResourceManager.GetString("FormatResetDescription", resourceCulture);
            }
        }
        
        internal static string AlignLeftDescription {
            get {
                return ResourceManager.GetString("AlignLeftDescription", resourceCulture);
            }
        }
        
        internal static string AlignRightDescription {
            get {
                return ResourceManager.GetString("AlignRightDescription", resourceCulture);
            }
        }
        
        internal static string AlignCentreDescription {
            get {
                return ResourceManager.GetString("AlignCentreDescription", resourceCulture);
            }
        }
        
        internal static string DatesDMYDescription {
            get {
                return ResourceManager.GetString("DatesDMYDescription", resourceCulture);
            }
        }
        
        internal static string DatesDMDescription {
            get {
                return ResourceManager.GetString("DatesDMDescription", resourceCulture);
            }
        }
        
        internal static string DatesMYDescription {
            get {
                return ResourceManager.GetString("DatesMYDescription", resourceCulture);
            }
        }
        
        internal static string FileEditDescription {
            get {
                return ResourceManager.GetString("FileEditDescription", resourceCulture);
            }
        }
        
        internal static string FileSaveDescription {
            get {
                return ResourceManager.GetString("FileSaveDescription", resourceCulture);
            }
        }
        
        internal static string SetColumnWidthDescription {
            get {
                return ResourceManager.GetString("SetColumnWidthDescription", resourceCulture);
            }
        }
        
        internal static string ResetColumnWidthDescription {
            get {
                return ResourceManager.GetString("ResetColumnWidthDescription", resourceCulture);
            }
        }
        
        internal static string QuitCalc {
            get {
                return ResourceManager.GetString("QuitCalc", resourceCulture);
            }
        }
        
        internal static string EnterDecimalPlaces {
            get {
                return ResourceManager.GetString("EnterDecimalPlaces", resourceCulture);
            }
        }
        
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        internal static string SettingsColours {
            get {
                return ResourceManager.GetString("SettingsColours", resourceCulture);
            }
        }
        
        internal static string SettingsFormat {
            get {
                return ResourceManager.GetString("SettingsFormat", resourceCulture);
            }
        }
        
        internal static string SettingsAlignment {
            get {
                return ResourceManager.GetString("SettingsAlignment", resourceCulture);
            }
        }
        
        internal static string SettingsDecimalPoints {
            get {
                return ResourceManager.GetString("SettingsDecimalPoints", resourceCulture);
            }
        }
        
        internal static string SettingsBackups {
            get {
                return ResourceManager.GetString("SettingsBackups", resourceCulture);
            }
        }
        
        internal static string InvalidColourIndex {
            get {
                return ResourceManager.GetString("InvalidColourIndex", resourceCulture);
            }
        }
        
        internal static string FormatTextDescription {
            get {
                return ResourceManager.GetString("FormatTextDescription", resourceCulture);
            }
        }
        
        internal static string SettingsColourDescription {
            get {
                return ResourceManager.GetString("SettingsColourDescription", resourceCulture);
            }
        }
        
        internal static string SettingsFormatDescription {
            get {
                return ResourceManager.GetString("SettingsFormatDescription", resourceCulture);
            }
        }
        
        internal static string SettingsAlignmentDescription {
            get {
                return ResourceManager.GetString("SettingsAlignmentDescription", resourceCulture);
            }
        }
        
        internal static string SettingsDecimalPointDescription {
            get {
                return ResourceManager.GetString("SettingsDecimalPointDescription", resourceCulture);
            }
        }
        
        internal static string SettingsBackupDescription {
            get {
                return ResourceManager.GetString("SettingsBackupDescription", resourceCulture);
            }
        }
        
        internal static string DeleteColumnDescription {
            get {
                return ResourceManager.GetString("DeleteColumnDescription", resourceCulture);
            }
        }
        
        internal static string DeleteRowDescription {
            get {
                return ResourceManager.GetString("DeleteRowDescription", resourceCulture);
            }
        }
        
        internal static string FileExport {
            get {
                return ResourceManager.GetString("FileExport", resourceCulture);
            }
        }
        
        internal static string FileExportDescription {
            get {
                return ResourceManager.GetString("FileExportDescription", resourceCulture);
            }
        }
        
        internal static string ExportFilename {
            get {
                return ResourceManager.GetString("ExportFilename", resourceCulture);
            }
        }
        
        internal static string Calc_FileImportDescription {
            get {
                return ResourceManager.GetString("Calc_FileImportDescription", resourceCulture);
            }
        }
        
        internal static string FileImport {
            get {
                return ResourceManager.GetString("FileImport", resourceCulture);
            }
        }
        
        internal static string EnterImportFilename {
            get {
                return ResourceManager.GetString("EnterImportFilename", resourceCulture);
            }
        }
        
        internal static string CannotSaveConfigError {
            get {
                return ResourceManager.GetString("CannotSaveConfigError", resourceCulture);
            }
        }
        
        internal static string BadCSVImportFile {
            get {
                return ResourceManager.GetString("BadCSVImportFile", resourceCulture);
            }
        }
        
        internal static string ErrorReadingFile {
            get {
                return ResourceManager.GetString("ErrorReadingFile", resourceCulture);
            }
        }
        
        internal static string ErrorExportingFile {
            get {
                return ResourceManager.GetString("ErrorExportingFile", resourceCulture);
            }
        }
        
        internal static string EnterBackgroundColour {
            get {
                return ResourceManager.GetString("EnterBackgroundColour", resourceCulture);
            }
        }
        
        internal static string EnterForegroundColour {
            get {
                return ResourceManager.GetString("EnterForegroundColour", resourceCulture);
            }
        }
        
        internal static string EnterMessageColour {
            get {
                return ResourceManager.GetString("EnterMessageColour", resourceCulture);
            }
        }
        
        internal static string EnterSelectionColour {
            get {
                return ResourceManager.GetString("EnterSelectionColour", resourceCulture);
            }
        }
        
        internal static string BackgroundColourError {
            get {
                return ResourceManager.GetString("BackgroundColourError", resourceCulture);
            }
        }
        
        internal static string CreateBackupFilePrompt {
            get {
                return ResourceManager.GetString("CreateBackupFilePrompt", resourceCulture);
            }
        }
        
        internal static string RangeExportDescription {
            get {
                return ResourceManager.GetString("RangeExportDescription", resourceCulture);
            }
        }
        
        internal static string RangeExport {
            get {
                return ResourceManager.GetString("RangeExport", resourceCulture);
            }
        }
        
        internal static string RangeSortDescription {
            get {
                return ResourceManager.GetString("RangeSortDescription", resourceCulture);
            }
        }
        
        internal static string FormFieldInputRange {
            get {
                return ResourceManager.GetString("FormFieldInputRange", resourceCulture);
            }
        }
        
        internal static string RangeSort {
            get {
                return ResourceManager.GetString("RangeSort", resourceCulture);
            }
        }
    }
}
