//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JCalc.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Calc {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Calc() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("calc.Resources.Calc", typeof(Calc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string NewFileWarning {
            get {
                return ResourceManager.GetString("NewFileWarning", resourceCulture);
            }
        }
        
        internal static string NewFile {
            get {
                return ResourceManager.GetString("NewFile", resourceCulture);
            }
        }
        
        internal static string QuitPrompt {
            get {
                return ResourceManager.GetString("QuitPrompt", resourceCulture);
            }
        }
        
        internal static string SelectOptionPrompt {
            get {
                return ResourceManager.GetString("SelectOptionPrompt", resourceCulture);
            }
        }
        
        internal static string GotoPrompt {
            get {
                return ResourceManager.GetString("GotoPrompt", resourceCulture);
            }
        }
        
        internal static string GotoRowPrompt {
            get {
                return ResourceManager.GetString("GotoRowPrompt", resourceCulture);
            }
        }
        
        internal static string GotoColumnPrompt {
            get {
                return ResourceManager.GetString("GotoColumnPrompt", resourceCulture);
            }
        }
        
        internal static string EnterNumber {
            get {
                return ResourceManager.GetString("EnterNumber", resourceCulture);
            }
        }
        
        internal static string GotoMacro {
            get {
                return ResourceManager.GetString("GotoMacro", resourceCulture);
            }
        }
        
        internal static string GotoName {
            get {
                return ResourceManager.GetString("GotoName", resourceCulture);
            }
        }
        
        internal static string GotoRowCol {
            get {
                return ResourceManager.GetString("GotoRowCol", resourceCulture);
            }
        }
        
        internal static string GotoWindow {
            get {
                return ResourceManager.GetString("GotoWindow", resourceCulture);
            }
        }
        
        internal static string NotAValidOption {
            get {
                return ResourceManager.GetString("NotAValidOption", resourceCulture);
            }
        }
        
        internal static string Alpha {
            get {
                return ResourceManager.GetString("Alpha", resourceCulture);
            }
        }
        
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        internal static string AlphaValue {
            get {
                return ResourceManager.GetString("AlphaValue", resourceCulture);
            }
        }
        
        internal static string EnterText {
            get {
                return ResourceManager.GetString("EnterText", resourceCulture);
            }
        }
        
        internal static string EnterTextOrValue {
            get {
                return ResourceManager.GetString("EnterTextOrValue", resourceCulture);
            }
        }
        
        internal static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        internal static string FormatCells {
            get {
                return ResourceManager.GetString("FormatCells", resourceCulture);
            }
        }
        
        internal static string FormatDefault {
            get {
                return ResourceManager.GetString("FormatDefault", resourceCulture);
            }
        }
        
        internal static string FormatOptions {
            get {
                return ResourceManager.GetString("FormatOptions", resourceCulture);
            }
        }
        
        internal static string FormatWidth {
            get {
                return ResourceManager.GetString("FormatWidth", resourceCulture);
            }
        }
        
        internal static string CmdbarFilename {
            get {
                return ResourceManager.GetString("CmdbarFilename", resourceCulture);
            }
        }
        
        internal static string FormatWidthPrompt {
            get {
                return ResourceManager.GetString("FormatWidthPrompt", resourceCulture);
            }
        }
        
        internal static string FormatWidthColumn {
            get {
                return ResourceManager.GetString("FormatWidthColumn", resourceCulture);
            }
        }
        
        internal static string FormatWidthThrough {
            get {
                return ResourceManager.GetString("FormatWidthThrough", resourceCulture);
            }
        }
        
        internal static string FormatDefaultCells {
            get {
                return ResourceManager.GetString("FormatDefaultCells", resourceCulture);
            }
        }
        
        internal static string FormatAlignment {
            get {
                return ResourceManager.GetString("FormatAlignment", resourceCulture);
            }
        }
        
        internal static string FormatCode {
            get {
                return ResourceManager.GetString("FormatCode", resourceCulture);
            }
        }
        
        internal static string FormatDecimals {
            get {
                return ResourceManager.GetString("FormatDecimals", resourceCulture);
            }
        }
    }
}
